//Monitor
export const MONITOR_RES_ID = "MONITOR_RES_ID";
export const MONITOR_RES_INFO = "MONITOR_RES_INFO";
export const MONITOR_SERVER_BASIC_INFO = "MONITOR_BASIC_INFO";
export const MONITOR_SERVER_CPU_USAGE = "MONITOR_CPU_USAGE";
export const MONITOR_SERVER_MEM_USAGE = "MONITOR_MEM_USAGE";
export const MONITOR_SERVER_FILE_SYSTEM_USAGE = "MONITOR_FILE_SYSTEM_USAGE";
export const MONITOR_SERVER_DISK_IO = "MONITOR_DISK_IO";
export const MONITOR_SERVER_NETWORK_IO = "MONITOR_NETWORK_IO";
export const MONITOR_SERVER_PROCESS = "MONITOR_PROCESS";

export const MONITOR_SERVER_BASIC_INFO_LOADER = "MONITOR_BASIC_INFO_LOADER";
export const MONITOR_SERVER_CPU_USAGE_LOADER = "MONITOR_CPU_USAGE_LOADER";
export const MONITOR_SERVER_MEM_USAGE_LOADER = "MONITOR_MEM_USAGE_LOADER";
export const MONITOR_SERVER_FILE_SYSTEM_USAGE_LOADER = "MONITOR_FILE_SYSTEM_USAGE_LOADER";
export const MONITOR_SERVER_DISK_IO_LOADER = "MONITOR_DISK_IO_LOADER";
export const MONITOR_SERVER_NETWORK_IO_LOADER = "MONITOR_NETWORK_IO_LOADER";
export const MONITOR_SERVER_PROCESS_LOADER = "MONITOR_PROCESS_LOADER";

export const MONITOR_CLEAR_DATA = "MONITOR_CLEAR_DATA"

//Resource
export const RES_DEVICE_LIST = "RES_DEVICE_LIST";
export const RES_SERVICE_LIST = "RES_SERVICE_LIST";
export const RES_GROUP_LIST = "RES_GROUP_LIST";
export const RES_TOPOLOGY_LIST = "RES_TOPOLOGY_LIST";
export const RES_DEFAULT_SERVER = "RES_DEFAULT_SERVER";

//Navigaitor
export const NAV_BREADCRUMB_MODULE = "MONITOR_BREADCRUMB_MODULE"
export const NAV_BREADCRUMB_RES = "MONITOR_BREADCRUMB_RES"


//Topology
export const TOPO_LOAD_DATA = "TOPO_LOAD_DATA"
export const TOPO_UPDATE_NODES = "TOPO_UPDATE_NODES"
export const TOPO_DELETE_NODES = "TOPO_DELETE_NODES"
export const TOPO_DELETE_EDGES = "TOPO_DELETE_EDGES"
export const TOPO_UPDATE_EDGES = "TOPO_UPDATE_EDGES"
export const TOPO_LOAD_STATUS = "TOPO_LOAD_STATUS"
export const TOPO_SAVE_STATUS = "TOPO_SAVE_STATUS"